spring.application.name=backend

# JWT Configuration
taskmanager.app.jwtSecret=YourSecretKeyForSigningTokensMustBeAtLeast32CharactersLong
taskmanager.app.jwtExpirationMs=86400000

# Database (Railway will provide these)
spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb
spring.datasource.username=postgres
spring.datasource.password=$Postgre#Sql@230
spring.jpa.hibernate.ddl-auto=update